//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rinjani.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rinjani.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least two brokers must be enabled..
        /// </summary>
        public static string AtLeastTwoBrokersMustBeEnabled {
            get {
                return ResourceManager.GetString("AtLeastTwoBrokersMustBeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available volume.
        /// </summary>
        public static string AvailableVolume {
            get {
                return ResourceManager.GetString("AvailableVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available volume is smaller than min size..
        /// </summary>
        public static string AvailableVolumeIsSmallerThanMinSize {
            get {
                return ResourceManager.GetString("AvailableVolumeIsSmallerThanMinSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best ask.
        /// </summary>
        public static string BestAsk {
            get {
                return ResourceManager.GetString("BestAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best bid.
        /// </summary>
        public static string BestBid {
            get {
                return ResourceManager.GetString("BestBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;Both legs are successfully filled..
        /// </summary>
        public static string BothLegsAreSuccessfullyFilled {
            get {
                return ResourceManager.GetString("BothLegsAreSuccessfullyFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;Buy fill price is {0}..
        /// </summary>
        public static string BuyFillPriceIs {
            get {
                return ResourceManager.GetString("BuyFillPriceIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;Buy leg is not filled yet. Pending size is {0}..
        /// </summary>
        public static string BuyLegIsNotFilledYetPendingSizeIs {
            get {
                return ResourceManager.GetString("BuyLegIsNotFilledYetPendingSizeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;Checking if both legs are done or not....
        /// </summary>
        public static string CheckingIfBothLegsAreDoneOrNot {
            get {
                return ResourceManager.GetString("CheckingIfBothLegsAreDoneOrNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected profit.
        /// </summary>
        public static string ExpectedProfit {
            get {
                return ResourceManager.GetString("ExpectedProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get a spread analysis result. {0}.
        /// </summary>
        public static string FailedToGetASpreadAnalysisResult {
            get {
                return ResourceManager.GetString("FailedToGetASpreadAnalysisResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;Found arbitrage oppotunity..
        /// </summary>
        public static string FoundArbitrageOppotunity {
            get {
                return ResourceManager.GetString("FoundArbitrageOppotunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found inverted quotes..
        /// </summary>
        public static string FoundInvertedQuotes {
            get {
                return ResourceManager.GetString("FoundInvertedQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LongAllowed.
        /// </summary>
        public static string LongAllowed {
            get {
                return ResourceManager.GetString("LongAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for opportunity....
        /// </summary>
        public static string LookingForOpportunity {
            get {
                return ResourceManager.GetString("LookingForOpportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max retry count reached. Cancelling the pending orders..
        /// </summary>
        public static string MaxRetryCountReachedCancellingThePendingOrders {
            get {
                return ResourceManager.GetString("MaxRetryCountReachedCancellingThePendingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net exposure is larger than max net exposure..
        /// </summary>
        public static string NetExposureIsLargerThanMaxNetExposure {
            get {
                return ResourceManager.GetString("NetExposureIsLargerThanMaxNetExposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No arbitrage opportunity. Spread is not inverted..
        /// </summary>
        public static string NoArbitrageOpportunitySpreadIsNotInverted {
            get {
                return ResourceManager.GetString("NoArbitrageOpportunitySpreadIsNotInverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No best ask was found..
        /// </summary>
        public static string NoBestAskWasFound {
            get {
                return ResourceManager.GetString("NoBestAskWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No best bid was found..
        /// </summary>
        public static string NoBestBidWasFound {
            get {
                return ResourceManager.GetString("NoBestBidWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;Order check attempt {0}..
        /// </summary>
        public static string OrderCheckAttempt {
            get {
                return ResourceManager.GetString("OrderCheckAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;Profit is {0}..
        /// </summary>
        public static string ProfitIs {
            get {
                return ResourceManager.GetString("ProfitIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;Sell fill price is {0}..
        /// </summary>
        public static string SellFillPriceIs {
            get {
                return ResourceManager.GetString("SellFillPriceIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;Sell leg is not filled yet. Pending size is {0}..
        /// </summary>
        public static string SellLegIsNotFilledYetPendingSizeIs {
            get {
                return ResourceManager.GetString("SellLegIsNotFilledYetPendingSizeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;Sending order targetting quote {0}....
        /// </summary>
        public static string SendingOrderTargettingQuote {
            get {
                return ResourceManager.GetString("SendingOrderTargettingQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShortAllowed.
        /// </summary>
        public static string ShortAllowed {
            get {
                return ResourceManager.GetString("ShortAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;Sleeping {0} after send..
        /// </summary>
        public static string SleepingAfterSend {
            get {
                return ResourceManager.GetString("SleepingAfterSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spread.
        /// </summary>
        public static string Spread {
            get {
                return ResourceManager.GetString("Spread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started {0}..
        /// </summary>
        public static string StartedArbitrager {
            get {
                return ResourceManager.GetString("StartedArbitrager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting {0}....
        /// </summary>
        public static string StartingArbitrager {
            get {
                return ResourceManager.GetString("StartingArbitrager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the service....
        /// </summary>
        public static string StartingTheService {
            get {
                return ResourceManager.GetString("StartingTheService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping the service....
        /// </summary>
        public static string StoppingTheService {
            get {
                return ResourceManager.GetString("StoppingTheService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully started the service..
        /// </summary>
        public static string SuccessfullyStartedTheService {
            get {
                return ResourceManager.GetString("SuccessfullyStartedTheService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully stopped the service..
        /// </summary>
        public static string SuccessfullyStoppedTheService {
            get {
                return ResourceManager.GetString("SuccessfullyStoppedTheService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target profit is smaller than min profit..
        /// </summary>
        public static string TargetProfitIsSmallerThanMinProfit {
            get {
                return ResourceManager.GetString("TargetProfitIsSmallerThanMinProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target volume.
        /// </summary>
        public static string TargetVolume {
            get {
                return ResourceManager.GetString("TargetVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;This is Demo mode. Not sending orders..
        /// </summary>
        public static string ThisIsDemoModeNotSendingOrders {
            get {
                return ResourceManager.GetString("ThisIsDemoModeNotSendingOrders", resourceCulture);
            }
        }
    }
}
